apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-nginx-ingress
  namespace: hamravesh-samurai
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "400"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: snapp-store-traefik
  rules:
    - host: "*.bardia-rk.ir"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
  tls:
    - hosts:
        - "*.bardia-rk.ir"
      secretName: bardia-rk-wildcard-tls
