apiVersion: v1
kind: Service
metadata:
  name: splunk
spec:
  selector:
    app: splunk
  ports:
    - name: web
      port: 8000
      targetPort: 8000
    - name: mgmt
      port: 8089
      targetPort: 8089
    - name: forwarder
      port: 9997
      targetPort: 9997
  type: ClusterIP

